"""add datetime column to task

Revision ID: 15388eecc3e7
Revises: 65d9b78c90c5
Create Date: 2018-02-21 14:42:37.314255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15388eecc3e7'
down_revision = '65d9b78c90c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'timestamp')
    # ### end Alembic commands ###
