"""new start

Revision ID: 65d9b78c90c5
Revises: 
Create Date: 2018-02-17 17:02:21.362184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d9b78c90c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=20), nullable=True),
    sa.Column('comments', sa.String(length=64), nullable=True),
    sa.Column('category_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('timeperiod', sa.String(length=20), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('release', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_desc'), 'task', ['desc'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_timeperiod'), 'task', ['timeperiod'], unique=False)
    op.create_index(op.f('ix_task_title'), 'task', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_title'), table_name='task')
    op.drop_index(op.f('ix_task_timeperiod'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_desc'), table_name='task')
    op.drop_table('task')
    op.drop_table('category')
    # ### end Alembic commands ###
