"""2 new columns to task

Revision ID: 93280e712da3
Revises: a9707bc9e6d6
Create Date: 2017-10-07 19:32:42.275439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93280e712da3'
down_revision = 'a9707bc9e6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('category', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('cost_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'cost_time')
    op.drop_column('task', 'category')
    # ### end Alembic commands ###
